/**
 * Gallery data for /gallery and /solar-gallery.
 * Uses build-time manifest (scripts/generate-gallery-manifest.js) so no fs/path
 * are bundled into the Vercel function (avoids 300MB size limit).
 */

import type { GalleryItem, GalleryItemWithTown } from "@/config/gallery";
import { GALLERY_DESCRIPTIONS } from "@/config/gallery-descriptions";
import { seoTowns } from "@/config/seo-towns";

/** Build-time manifest; generated by scripts/generate-gallery-manifest.js */
import manifestData from "@/data/gallery-manifest.json";

const DEFAULT_ALT_SUFFIX = " – Fennor Developments";
const DEFAULT_DESCRIPTION =
  "Solar PV, electrical or construction installation – Fennor Developments, Meath and Ireland.";

type ManifestItem = { src: string; thumbSrc: string | null; caption: string };

function getFilename(src: string): string {
  const parts = src.split("/");
  return parts[parts.length - 1] ?? src;
}

/** Returns every gallery image (from manifest + descriptions). No fs. */
export function getGalleryImages(): GalleryItem[] {
  const manifest = (manifestData as ManifestItem[]) ?? [];
  return manifest.map((m) => {
    const filename = getFilename(m.src);
    const custom = GALLERY_DESCRIPTIONS[filename];
    const alt = custom?.description ?? `${m.caption}${DEFAULT_ALT_SUFFIX}`;
    const description = custom?.description ?? DEFAULT_DESCRIPTION;
    return {
      src: m.src,
      thumbSrc: m.thumbSrc ?? undefined,
      alt,
      caption: m.caption,
      description,
    };
  });
}

/** SEO alt text for a gallery image assigned to a town. */
export function getGalleryImageAltForTown(town: string): string {
  return `Solar panel installation ${town}, solar PV installers ${town} – Fennor Developments`;
}

/** Gallery images with town assigned for location SEO (alt, JSON-LD). */
export function getGalleryImagesWithSeo(): GalleryItemWithTown[] {
  const images = getGalleryImages();
  return images.map((item, index) => {
    const town = seoTowns[index % seoTowns.length];
    return {
      ...item,
      town,
      alt: getGalleryImageAltForTown(town),
    };
  });
}
